AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upb-lambda
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: s3://gabodeployments2/efab3420442d544eab817e63fed6081e
